# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
from Trading_Systeam import GUI_Trading_systeam
from PyQt6.QtCore import QThread


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1083, 662)
        self.trade_info = QtWidgets.QTextEdit(Form)
        self.trade_info.setGeometry(QtCore.QRect(170, 40, 871, 601))
        self.trade_info.setReadOnly(True)
        self.trade_info.setObjectName("trade_info")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 20, 131, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_trade = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.btn_trade.setFont(font)
        self.btn_trade.setStyleSheet("background-color: rgb(140, 215, 144);\n"
                                     "color: rgb(255, 255, 255);")
        self.btn_trade.setObjectName("btn_trade")
        self.btn_trade.clicked.connect(self.click_btn_trade)

        self.verticalLayout.addWidget(self.btn_trade)
        self.btn_savedata = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_savedata.setFont(font)
        self.btn_savedata.setStyleSheet("background-color: rgb(238, 119, 133);\n"
                                        "color: rgb(255, 255, 255);")
        self.btn_savedata.setObjectName("btn_savedata")
        self.btn_savedata.clicked.connect(self.click_save_data)

        self.verticalLayout.addWidget(self.btn_savedata)
        self.btn_reloaddata = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_reloaddata.setFont(font)
        self.btn_reloaddata.setStyleSheet("color: rgb(255, 255, 255);\n"
                                          "background-color: rgb(191, 200, 234);")
        self.btn_reloaddata.setObjectName("btn_reloaddata")
        self.verticalLayout.addWidget(self.btn_reloaddata)
        self.btn_Portfolio = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_Portfolio.setFont(font)
        self.btn_Portfolio.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(102, 139, 196);")
        self.btn_Portfolio.setObjectName("btn_Portfolio")
        self.verticalLayout.addWidget(self.btn_Portfolio)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Binance trade systeam"))
        self.trade_info.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.trade_info.setPlaceholderText(_translate("Form", "程序尚未運行..."))
        self.btn_trade.setText(_translate("Form", "啟動程序"))
        self.btn_savedata.setText(_translate("Form", "關閉程序"))
        self.btn_reloaddata.setText(_translate("Form", "重新回補"))
        self.btn_Portfolio.setText(_translate("Form", "投資組合回測"))

    def click_btn_trade(self):
        self.systeam = GUI_Trading_systeam(self)
        self.Trading_systeam_Thread = QThread()
        self.Trading_systeam_Thread.run = self.systeam.main
        self.Trading_systeam_Thread.start()

    def print_info(self, *args):
        out_str = ''
        for i in args:
            out_str += str(i)+" "
            print("GUI測試進入", out_str)
            self.trade_info.append(out_str)

    def click_save_data(self):
        """ 保存資料並關閉程序 注意不能使用replace 資料長短問題"""
        for name, each_df in self.systeam.symbol_map.items():
            pass
            # self.systeam.dataprovider_online.save_data(
            #     symbol_name=name, original_df=each_df)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)

    Form.show()
    sys.exit(app.exec())
