# Form implementation generated from reading ui file '.\GUI\Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 509)
        self.pushButton_login = QtWidgets.QPushButton(Dialog)
        self.pushButton_login.setGeometry(QtCore.QRect(30, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("background-color: rgb(162, 158, 154);\n"
                                            "color: rgb(255, 255, 255);")
        self.pushButton_login.setObjectName("pushButton_login")
        self.checkBox_remeberpa = QtWidgets.QCheckBox(Dialog)
        self.checkBox_remeberpa.setGeometry(QtCore.QRect(30, 340, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_remeberpa.setFont(font)
        self.checkBox_remeberpa.setObjectName("checkBox_remeberpa")
        self.pushButton_CheckDate = QtWidgets.QPushButton(Dialog)
        self.pushButton_CheckDate.setGeometry(QtCore.QRect(200, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_CheckDate.setFont(font)
        self.pushButton_CheckDate.setStyleSheet("background-color: rgb(85, 170, 0);\n"
                                                "color: rgb(255, 255, 255);")
        self.pushButton_CheckDate.setObjectName("pushButton_CheckDate")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 20, 343, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_accout = QtWidgets.QLabel(self.widget)
        self.label_accout.setMinimumSize(QtCore.QSize(191, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_accout.setFont(font)
        self.label_accout.setObjectName("label_accout")
        self.verticalLayout.addWidget(self.label_accout)
        self.lineEdit_api_key = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_api_key.setMinimumSize(QtCore.QSize(341, 40))
        self.lineEdit_api_key.setObjectName("lineEdit_api_key")
        self.verticalLayout.addWidget(self.lineEdit_api_key)
        self.label_secret_key = QtWidgets.QLabel(self.widget)
        self.label_secret_key.setMinimumSize(QtCore.QSize(301, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_secret_key.setFont(font)
        self.label_secret_key.setObjectName("label_secret_key")
        self.verticalLayout.addWidget(self.label_secret_key)
        self.lineEdit_secret_key = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_secret_key.setMinimumSize(QtCore.QSize(321, 40))
        self.lineEdit_secret_key.setObjectName("lineEdit_secret_key")
        self.verticalLayout.addWidget(self.lineEdit_secret_key)
        self.label_LINE = QtWidgets.QLabel(self.widget)
        self.label_LINE.setMinimumSize(QtCore.QSize(181, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_LINE.setFont(font)
        self.label_LINE.setObjectName("label_LINE")
        self.verticalLayout.addWidget(self.label_LINE)
        self.lineEdit_LINE = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_LINE.setMinimumSize(QtCore.QSize(301, 40))
        self.lineEdit_LINE.setObjectName("lineEdit_LINE")
        self.verticalLayout.addWidget(self.lineEdit_LINE)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_login.setText(_translate("Dialog", "Login"))
        self.checkBox_remeberpa.setText(_translate("Dialog", "請記住帳號密碼"))
        self.pushButton_CheckDate.setText(_translate("Dialog", "CheckDate"))
        self.label_accout.setText(_translate("Dialog", "Binance API_KEY"))
        self.label_secret_key.setText(
            _translate("Dialog", "Binance Secret Key"))
        self.label_LINE.setText(_translate("Dialog", "LINE Notify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
