# Form implementation generated from reading ui file '.\MainWindow_TC.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1154, 667)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 761, 531))
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(860, 40, 252, 531))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NowMonitorStrategy_from = QtWidgets.QTableView(self.widget)
        self.NowMonitorStrategy_from.setMaximumSize(QtCore.QSize(250, 400))
        self.NowMonitorStrategy_from.setObjectName("NowMonitorStrategy_from")
        self.verticalLayout.addWidget(self.NowMonitorStrategy_from)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setMaximumSize(QtCore.QSize(250, 400))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1154, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        
        self.actionimport = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI\Images\ImportData.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionimport.setIcon(icon)
        self.actionimport.setObjectName("actionimport")
        
        
        self.actionexport = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI\Images\CsvExport.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionexport.setIcon(icon1)
        self.actionexport.setObjectName("actionexport")
        
        
        
        self.actionAutoTrading = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI\Images\Gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionAutoTrading.setIcon(icon2)
        self.actionAutoTrading.setObjectName("actionAutoTrading")
        
        
        
        self.actionSaveData = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("GUI\Images\SaveData.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSaveData.setIcon(icon3)
        self.actionSaveData.setObjectName("actionSaveData")
        self.actionReload_Day_Data = QtGui.QAction(MainWindow)
        self.actionReload_Day_Data.setObjectName("actionReload_Day_Data")
        self.actionReload_Min_Data = QtGui.QAction(MainWindow)
        self.actionReload_Min_Data.setObjectName("actionReload_Min_Data")
        self.menuFile.addAction(self.actionimport)
        self.menuFile.addAction(self.actionexport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAutoTrading)
        self.menuFile.addAction(self.actionSaveData)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReload_Day_Data)
        self.menuFile.addAction(self.actionReload_Min_Data)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionAutoTrading)
        self.toolBar.addAction(self.actionSaveData)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionimport)
        self.toolBar.addAction(self.actionexport)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crypto Trading Systeam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "CloseProfit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionimport.setText(_translate("MainWindow", "Import"))
        self.actionexport.setText(_translate("MainWindow", "Export"))
        self.actionAutoTrading.setText(_translate("MainWindow", "AutoTrading"))
        self.actionSaveData.setText(_translate("MainWindow", "SaveData"))
        self.actionReload_Day_Data.setText(_translate("MainWindow", "Reload Day Data"))
        self.actionReload_Min_Data.setText(_translate("MainWindow", "Reload Min Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
